### ISSUE TITLE
Tests on Windows so far

### ISSUE THREAD

**Issue by DiegoJArg** [emoon/minifb#103]
Hi.
I just compiled it with MinGW to test it out and see what is it about.

These were my steps if anyone else is interested.
```
cmake -S . -G "MinGW Makefiles" -DUSE_OPENGL_API=OFF --fresh
```

To remove the cmd.exe, adding `-DCMAKE_C_FLAGS="-mwindows"` didn't worked. It was required to edit the CMakeLists.txt to add `WIN32` flag to `add_executable`

```
add_executable(noise WIN32
    tests/noise.c
)
```

I really like the portability shown here and that it abstracts the handling of the window creation.
For example, on Windows I am able to choose to link to GDI or to WGL (which also links to GDI).

However, from the readme, I keep wondering what libraries can be used on top of it in order to see real world applications. Are there real world examples? A list of Could it work as backend for ImGUI libraries ? Is there any 'mini' ImGUI library that would match well with it?

Kind regards

**Comment by Darky-Lucera** [comment]
Hello,

I am pleased to inform you that the software compiles and runs seamlessly on both MSVC 2022 and MinGW on Windows without requiring any modifications. The flag WIN32 is only used when opting to use a WinMain entry point instead of a main. It is not a requirement for using MiniFB and it is entirely up to your personal preference. This flag is a custom CMake flag.

This library offers a framebuffer and if you wish to use ImGUI, you will need to use a software renderer. While there are numerous people utilizing MiniFB for real-world projects, we do not have a comprehensive list of these projects.

Thank you and Best regards.
